name: release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build_to_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Fetch tags
        run: |
          git fetch --prune --unshallow --tags

      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Make plik release
        run: make release

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          files: releases/*
